# BoTorch-MODEL

In [1]:
DATA = "march_nsgp" # or "prev"

- python train.py [Fold] [Kernel] [Random_state] [DATA] 

- python test.py [Fold] [Kernel] [Best-Model-Path] [DATA] 


# RBF

In [ ]:
for i in range(10):
    !python train_ngpu.py 0 rbf {i} {DATA}

Traceback (most recent call last):
  File "train_ngpu.py", line 122, in <module>
    random_state = int(sys.argv[3])
ValueError: invalid literal for int() with base 10: '{i}'
Traceback (most recent call last):
  File "train_ngpu.py", line 122, in <module>
    random_state = int(sys.argv[3])
ValueError: invalid literal for int() with base 10: '{i}'
^C
Traceback (most recent call last):
  File "train_ngpu.py", line 10, in <module>
    import pandas as pd
  File "/opt/conda/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/opt/conda/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/opt/conda/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/opt/conda/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa


In [11]:
for i in range(10):
    !python train.py 1 rbf {i} {DATA}

Fold:  1
Random State:  0
100%|█████████████████████████████████████████| 400/400 [01:53<00:00,  3.53it/s]
Loss:  49.9731559753418
RMSE:  28.910533138254134
Fold:  1
Random State:  1
100%|█████████████████████████████████████████| 400/400 [01:54<00:00,  3.48it/s]
Loss:  77.77576446533203
RMSE:  28.55207550772869
Fold:  1
Random State:  2
100%|█████████████████████████████████████████| 400/400 [01:53<00:00,  3.53it/s]
Loss:  59.67097854614258
RMSE:  28.008763409155055
Fold:  1
Random State:  3
100%|█████████████████████████████████████████| 400/400 [01:53<00:00,  3.53it/s]
Loss:  63.928375244140625
RMSE:  27.168484532834434
Fold:  1
Random State:  4
100%|█████████████████████████████████████████| 400/400 [01:53<00:00,  3.53it/s]
Loss:  84.59952545166016
RMSE:  28.226414901406226
Fold:  1
Random State:  5
100%|█████████████████████████████████████████| 400/400 [01:53<00:00,  3.53it/s]
Loss:  65.48404693603516
RMSE:  28.329505340735277
Fold:  1
Random State:  6
100%|██████████████████████

In [12]:
for i in range(10):
    !python train.py 2 rbf {i} {DATA}

Fold:  2
Random State:  0
100%|█████████████████████████████████████████| 400/400 [01:54<00:00,  3.48it/s]
Loss:  48.903690338134766
RMSE:  25.343017062631983
Fold:  2
Random State:  1
100%|█████████████████████████████████████████| 400/400 [01:53<00:00,  3.52it/s]
Loss:  75.7704849243164
RMSE:  26.98226787244067
Fold:  2
Random State:  2
100%|█████████████████████████████████████████| 400/400 [01:53<00:00,  3.54it/s]
Loss:  57.15919494628906
RMSE:  25.856828408828523
Fold:  2
Random State:  3
100%|█████████████████████████████████████████| 400/400 [01:53<00:00,  3.53it/s]
Loss:  61.853492736816406
RMSE:  26.83932389981286
Fold:  2
Random State:  4
100%|█████████████████████████████████████████| 400/400 [01:53<00:00,  3.52it/s]
Loss:  82.38703155517578
RMSE:  25.864046994755046
Fold:  2
Random State:  5
100%|█████████████████████████████████████████| 400/400 [01:53<00:00,  3.53it/s]
Loss:  63.24044418334961
RMSE:  26.957832085819792
Fold:  2
Random State:  6
100%|██████████████████████

# Matern12

In [30]:
for i in range(1):
    !python train_ngpu.py 0 matern12 {i} {DATA}

Fold:  0
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:07<00:00,  3.14it/s]
Loss:  32.063880920410156
RMSE:  22.235481166953427
Fold:  0
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:07<00:00,  3.15it/s]
Loss:  53.44961929321289
RMSE:  22.931110272905673
Fold:  0
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:07<00:00,  3.13it/s]
Loss:  44.074363708496094
RMSE:  22.422667087448534


In [31]:
for i in range(1):
    !python train_ngpu.py 1 matern12 {i} {DATA}

Fold:  1
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:06<00:00,  3.15it/s]
Loss:  31.91702651977539
RMSE:  24.739210371589827


In [32]:
for i in range(1):
    !python train_ngpu.py 2 matern12 {i} {DATA}

Fold:  2
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:07<00:00,  3.15it/s]
Loss:  31.19717025756836
RMSE:  25.097884417488874


# Matern32

In [14]:
for i in range(10):
    !python train_ngpu.py 0 matern32 {i} {DATA}

Fold:  0
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:15<00:00,  2.96it/s]
Loss:  41.529388427734375
RMSE:  22.373941806858927
Fold:  0
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:15<00:00,  2.94it/s]
Loss:  69.58088684082031
RMSE:  24.093208210479037
Fold:  0
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:15<00:00,  2.94it/s]
Loss:  52.07084274291992
RMSE:  22.80024121135419
Fold:  0
Random State:  3
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:16<00:00,  2.92it/s]
Loss:  56.67520523071289
RMSE:  23.83747294047345
Fold:  0
Random State:  4
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:16<00:00,  2.93it/s]
Loss:  71.7279663

In [15]:
for i in range(10):
    !python train_ngpu.py 1 matern32 {i} {DATA}

Fold:  1
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:15<00:00,  2.94it/s]
Loss:  41.64674377441406
RMSE:  26.19526783995229
Fold:  1
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:15<00:00,  2.96it/s]
Loss:  70.70259857177734
RMSE:  26.600654671645714
Fold:  1
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:15<00:00,  2.95it/s]
Loss:  53.352760314941406
RMSE:  25.688086117528513
Fold:  1
Random State:  3
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:15<00:00,  2.95it/s]
Loss:  57.533409118652344
RMSE:  25.61240931101206
Fold:  1
Random State:  4
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:16<00:00,  2.94it/s]
Loss:  73.201911

In [16]:
for i in range(10):
    !python train_ngpu.py 2 matern32 {i} {DATA}

Fold:  2
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:15<00:00,  2.95it/s]
Loss:  40.4492073059082
RMSE:  25.48680146875191
Fold:  2
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:15<00:00,  2.95it/s]
Loss:  68.75161743164062
RMSE:  26.30146751546584
Fold:  2
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:15<00:00,  2.94it/s]
Loss:  51.05900955200195
RMSE:  25.622694864182353
Fold:  2
Random State:  3
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:15<00:00,  2.94it/s]
Loss:  55.588478088378906
RMSE:  26.09076681499129
Fold:  2
Random State:  4
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:16<00:00,  2.94it/s]
Loss:  70.706733703

# Matern52

In [17]:
for i in range(10):
    !python train_ngpu.py 0 matern52 {i} {DATA}

Fold:  0
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:22<00:00,  2.80it/s]
Loss:  43.97016143798828
RMSE:  22.42996020888957
Fold:  0
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:24<00:00,  2.77it/s]
Loss:  71.36625671386719
RMSE:  24.428174805382355
Fold:  0
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:23<00:00,  2.79it/s]
Loss:  53.72138595581055
RMSE:  22.954252647848545
Fold:  0
Random State:  3
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:22<00:00,  2.80it/s]
Loss:  58.29132843017578
RMSE:  24.093756390397637
Fold:  0
Random State:  4
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:26<00:00,  2.73it/s]
Loss:  75.4010238

In [18]:
for i in range(10):
    !python train_ngpu.py 1 matern52 {i} {DATA}

Fold:  1
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:24<00:00,  2.76it/s]
Loss:  44.09522247314453
RMSE:  26.982807219834406
Fold:  1
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:25<00:00,  2.76it/s]
Loss:  72.71797943115234
RMSE:  27.10078793257648
Fold:  1
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:24<00:00,  2.76it/s]
Loss:  55.103675842285156
RMSE:  26.326475571611624
Fold:  1
Random State:  3
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:24<00:00,  2.76it/s]
Loss:  59.320621490478516
RMSE:  26.086809765853456
Fold:  1
Random State:  4
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:24<00:00,  2.76it/s]
Loss:  76.90264

In [19]:
for i in range(10):
    !python train_ngpu.py 2 matern52 {i} {DATA}

Fold:  2
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:24<00:00,  2.78it/s]
Loss:  42.94363784790039
RMSE:  25.407131505713387
Fold:  2
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:24<00:00,  2.76it/s]
Loss:  70.69853210449219
RMSE:  26.41996757503835
Fold:  2
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:24<00:00,  2.76it/s]
Loss:  52.75325393676758
RMSE:  25.62775131528742
Fold:  2
Random State:  3
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:24<00:00,  2.77it/s]
Loss:  57.305423736572266
RMSE:  26.213703074617907
Fold:  2
Random State:  4
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:23<00:00,  2.78it/s]
Loss:  74.4531097

# Matern+Rbf

In [ ]:
for i in range(10):
    !python train_ngpu.py 0 matern_rbf {i} {DATA}

Fold:  0
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:34<00:00,  2.59it/s]
Loss:  24.50878143310547
RMSE:  23.672321056962804
Fold:  0
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:34<00:00,  2.59it/s]
Loss:  44.186614990234375
RMSE:  22.272124969197364
Fold:  0
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:35<00:00,  2.57it/s]
Loss:  33.00155258178711
RMSE:  25.071884783536365
Fold:  0
Random State:  3
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:34<00:00,  2.59it/s]
Loss:  38.26621627807617
RMSE:  24.90708005584245
Fold:  0
Random State:  4
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:34<00:00,  2.58it/s]
Loss:  39.746433

In [21]:
for i in range(10):
    !python train_ngpu.py 1 matern_rbf {i} {DATA}

Fold:  1
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.55it/s]
Loss:  25.321048736572266
RMSE:  25.981445307660366
Fold:  1
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:36<00:00,  2.56it/s]
Loss:  44.33037185668945
RMSE:  27.048563849432906
Fold:  1
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:36<00:00,  2.55it/s]
Loss:  34.364864349365234
RMSE:  25.33714567760614
Fold:  1
Random State:  3
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.55it/s]
Loss:  39.97404861450195
RMSE:  32.02102474699348
Fold:  1
Random State:  4
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.55it/s]
Loss:  42.192756

In [ ]:
for i in range(10):
    !python train_ngpu.py 2 matern_rbf {i} {DATA}

Fold:  2
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.55it/s]
Loss:  24.40970230102539
RMSE:  26.32038732115316
Fold:  2
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.54it/s]
Loss:  42.09291458129883
RMSE:  26.422816643310085
Fold:  2
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:36<00:00,  2.55it/s]
Loss:  33.886592864990234
RMSE:  27.160814277715495
Fold:  2
Random State:  3
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.55it/s]
Loss:  38.779579162597656
RMSE:  25.417750443682706
Fold:  2
Random State:  4
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:36<00:00,  2.56it/s]
Loss:  39.85746

In [ ]:
python train_ngpu.py 2 matern_rbf 9 {DATA}

# Matern*Rbf

In [3]:
for i in range(10):
    !python train_ngpu.py 0 maternXrbf {i} {DATA}

Fold:  0
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:38<00:00,  2.52it/s]
Loss:  44.44075012207031
RMSE:  23.379183511435922
Fold:  0
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:39<00:00,  2.51it/s]
Loss:  79.08614349365234
RMSE:  24.689282126434374
Fold:  0
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:39<00:00,  2.50it/s]
Loss:  60.159793853759766
RMSE:  23.887044191944817
Fold:  0
Random State:  3
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.54it/s]
Loss:  67.19532775878906
RMSE:  24.7487533550321
Fold:  0
Random State:  4
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.54it/s]
Loss:  81.2378845

In [4]:
for i in range(10):
    !python train_ngpu.py 1 maternXrbf {i} {DATA}

Fold:  1
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.54it/s]
Loss:  45.33794021606445
RMSE:  28.426958249880503
Fold:  1
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:39<00:00,  2.50it/s]
Loss:  81.917724609375
RMSE:  29.24371284215504
Fold:  1
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.53it/s]
Loss:  61.95417404174805
RMSE:  27.62149806585598
Fold:  1
Random State:  3
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:40<00:00,  2.49it/s]
Loss:  68.59915924072266
RMSE:  28.778987724130857
Fold:  1
Random State:  4
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:46<00:00,  2.40it/s]
Loss:  83.1987075805

In [5]:
for i in range(10):
    !python train_ngpu.py 2 maternXrbf {i} {DATA}

Fold:  2
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.54it/s]
Loss:  43.53270721435547
RMSE:  25.984832241605186
Fold:  2
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.54it/s]
Loss:  79.22278594970703
RMSE:  27.30191169882525
Fold:  2
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:40<00:00,  2.49it/s]
Loss:  59.454830169677734
RMSE:  26.461402619542223
Fold:  2
Random State:  3
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.54it/s]
Loss:  66.42056274414062
RMSE:  27.08966083880808
Fold:  2
Random State:  4
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.54it/s]
Loss:  79.9538650

# TESTING

In [21]:
kernel = "rbf"
RS = 0
for fold in [0,1,2]:
    !python test_ngpu.py {fold} {kernel} /home/nsgp_group/baselines_bo/final_models/march_nsgp_data/{kernel}_fold_{fold}_random_state_{RS} march_nsgp

Fold:  0
RMSE:  23.11186673126866
Saving to:  final_preds/march_nsgp_data/rbf_fold_0.csv.gz
Fold:  1
RMSE:  64.45875871446353
Saving to:  final_preds/march_nsgp_data/rbf_fold_1.csv.gz
Fold:  2
RMSE:  58.63771661695074
Saving to:  final_preds/march_nsgp_data/rbf_fold_2.csv.gz


In [28]:
kernel = "local_p_matern12"
RS = 0
fold = 0
!python test_ngpu.py {fold} {kernel} /home/nsgp_group/baselines_bo/final_models/march_nsgp_data/{kernel}_fold_{fold}_random_state_{RS} march_nsgp

Fold:  0
RMSE:  22.665243962608265
Parameter containing:
tensor([[0.5429]], device='cuda:0', requires_grad=True)
[Parameter containing:
tensor([7.0897], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.7093], device='cuda:0', requires_grad=True), Parameter containing:
tensor(7.6226, device='cuda:0', requires_grad=True), Parameter containing:
tensor([[ 1.4876,  1.1397,  1.9450,  4.0049,  2.9279, -0.5051]],
       device='cuda:0', requires_grad=True), Parameter containing:
tensor([[-4.0086]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([[0.5429]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([[2.9021, 6.0797]], device='cuda:0', requires_grad=True)]


In [18]:
kernel = "matern12"
RS = 0
fold = 0
!python test_ngpu.py {fold} {kernel} /home/nsgp_group/baselines_bo/final_models/march_nsgp_data/{kernel}_fold_{fold}_random_state_{RS} march_nsgp

Fold:  0
RMSE:  22.886925750497763
{}
{}


In [5]:
# LOCALLY PERIODIC KERNEL
for i in range(1):
    !python train_ngpu.py 0 local_p {i} {DATA}

['longitude', 'latitude', 'weather', 'temperature', 'humidity', 'wind_speed', 'wind_direction', 'delta_t']
Fold:  0
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:23<00:00,  2.79it/s]
Loss:  35.50748062133789
RMSE:  22.047243425624018


In [9]:
for i in range(5):
    !python train_ngpu.py 1 local_p {i} {DATA}

Fold:  1
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:25<00:00,  2.75it/s]
Loss:  35.15379333496094
RMSE:  27.14657898922616
Fold:  1
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:26<00:00,  2.74it/s]
Loss:  51.49993133544922
RMSE:  26.666307813739582
Fold:  1
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:30<00:00,  2.66it/s]
Loss:  44.41213607788086
RMSE:  26.6582895510393
Fold:  1
Random State:  3
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:27<00:00,  2.70it/s]
Loss:  45.4356803894043
RMSE:  26.413755022761187
Fold:  1
Random State:  4
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:27<00:00,  2.72it/s]
Loss:  62.5826683044

In [5]:
for i in range(1):
    !python train_ngpu.py 2 local_p {i} {DATA}

Fold:  2
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:28<00:00,  2.69it/s]
Loss:  34.28480529785156
RMSE:  24.838663679298914


In [26]:
# LOCALLY PERIODIC KERNEL with Matern12
for i in range(1):
    !python train_ngpu.py 0 local_p_matern12 {i} {DATA}

Fold:  0
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:34<00:00,  2.58it/s]
Loss:  29.012474060058594
RMSE:  22.665243962608265


In [4]:
for i in range(1):
    !python train_ngpu.py 1 local_p_matern12 {i} {DATA}

['longitude', 'latitude', 'weather', 'temperature', 'humidity', 'wind_speed', 'wind_direction', 'delta_t']
Fold:  1
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:32<00:00,  2.63it/s]
Loss:  29.42738151550293
RMSE:  25.300777724021412


In [8]:
for i in range(1):
    !python train_ngpu.py 2 local_p_matern12 {i} {DATA}

Fold:  2
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:35<00:00,  2.57it/s]
Loss:  28.327442169189453
RMSE:  25.614186786696035


In [65]:
kernel = "matern12"
RS = 0
for fold in [0]:
    !python test_ngpu.py {fold} {kernel} /home/nsgp_group/baselines_bo/final_models/march_nsgp_data/{kernel}_fold_{fold}_random_state_{RS} march_nsgp

['longitude', 'latitude', 'weather', 'temperature', 'humidity', 'wind_speed', 'wind_direction', 'delta_t']
Fold:  0
RMSE:  22.235481166953427


In [10]:
for i in range(3):
    !python train_ngpu.py 1 local_p_with_rbf {i} {DATA}

Fold:  1
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:36<00:00,  2.56it/s]
Loss:  34.33063507080078
RMSE:  27.08063556447951
Fold:  1
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:36<00:00,  2.56it/s]
Loss:  55.41059875488281
RMSE:  26.472000784492145
Fold:  1
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:36<00:00,  2.56it/s]
Loss:  47.88109588623047
RMSE:  26.905664428910168


In [11]:
for i in range(3):
    !python train_ngpu.py 2 local_p_with_rbf {i} {DATA}

Fold:  2
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:38<00:00,  2.52it/s]
Loss:  33.14033126831055
RMSE:  24.86097035648703
Fold:  2
Random State:  1
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:37<00:00,  2.54it/s]
Loss:  54.99959945678711
RMSE:  25.03040928379786
Fold:  2
Random State:  2
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:36<00:00,  2.56it/s]
Loss:  46.791255950927734
RMSE:  24.90465858341698


In [13]:
for fold in range(3):
    for i in range(1):
        !python train_ngpu.py {fold} local_p_with_matern12 {i} {DATA}

Fold:  0
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:45<00:00,  2.42it/s]
Loss:  28.90599822998047
RMSE:  22.60155159178252
Fold:  1
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:45<00:00,  2.42it/s]
Loss:  28.984880447387695
RMSE:  24.955686423362916
Fold:  2
Random State:  0
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:45<00:00,  2.41it/s]
Loss:  27.846054077148438
RMSE:  25.26945400952628


In [14]:
for fold in range(3):
    for i in range(5,7):
        !python train_ngpu.py {fold} local_p_with_matern12 {i} {DATA}

Fold:  0
Random State:  5
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:46<00:00,  2.40it/s]
Loss:  45.038883209228516
RMSE:  22.978661861012085
Fold:  0
Random State:  6
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:46<00:00,  2.40it/s]
Loss:  40.59265899658203
RMSE:  22.906740617732225
Fold:  1
Random State:  5
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:45<00:00,  2.42it/s]
Loss:  44.9982795715332
RMSE:  25.189961656136898
Fold:  1
Random State:  6
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:45<00:00,  2.42it/s]
Loss:  40.341461181640625
RMSE:  25.248299567103917
Fold:  2
Random State:  5
Number of devices: 2 -- Kernel partition size: 0
100%|█████████████████████████████████████████| 400/400 [02:46<00:00,  2.41it/s]
Loss:  44.70574

In [45]:
kernel = "local_p_with_matern12"
RS = 0
fold = 0
!python test_ngpu.py 0 local_p_with_matern12 /home/nsgp_group/baselines_bo/final_models/march_nsgp_data/local_p_with_matern12_fold_0_random_state_0 march_nsgp

Fold:  0
RMSE:  22.60155159178252
Saving to:  final_preds/march_nsgp_data/local_p_with_matern12_fold_0.csv.gz
