In [1]:
DATA = "march" # or "prev"

- python train.py [Fold] [Kernel] [Random_state] [DATA] 

- python test.py [Fold] [Kernel] [Best-Model-Path] [DATA] 


# RBF

In [11]:
for i in range(3):
    !python train.py 0 rbf {i} {DATA}

Fold:  0
Random State:  0
100%|█████████████████████████████████████████| 400/400 [01:03<00:00,  6.32it/s]
Loss:  95.59767150878906
RMSE:  37.788276466433835
Fold:  0
Random State:  1
100%|█████████████████████████████████████████| 400/400 [01:03<00:00,  6.31it/s]
Loss:  127.07063293457031
RMSE:  38.393663357846286
Fold:  0
Random State:  2
100%|█████████████████████████████████████████| 400/400 [01:03<00:00,  6.31it/s]
Loss:  119.06267547607422
RMSE:  39.268741703848505


In [12]:
for i in range(3):
    !python train.py 1 rbf {i} {DATA}

Fold:  1
Random State:  0
100%|█████████████████████████████████████████| 400/400 [01:03<00:00,  6.31it/s]
Loss:  98.9638900756836
RMSE:  49.547766112250045
Fold:  1
Random State:  1
100%|█████████████████████████████████████████| 400/400 [01:03<00:00,  6.34it/s]
Loss:  133.05599975585938
RMSE:  47.24333206284662
Fold:  1
Random State:  2
100%|█████████████████████████████████████████| 400/400 [01:03<00:00,  6.29it/s]
Loss:  124.73531341552734
RMSE:  46.834052011022486


In [13]:
for i in range(3):
    !python train.py 2 rbf {i} {DATA}

Fold:  2
Random State:  0
100%|█████████████████████████████████████████| 400/400 [01:03<00:00,  6.32it/s]
Loss:  98.44371795654297
RMSE:  39.18576343965728
Fold:  2
Random State:  1
100%|█████████████████████████████████████████| 400/400 [01:03<00:00,  6.28it/s]
Loss:  130.23046875
RMSE:  39.816814651714274
Fold:  2
Random State:  2
100%|█████████████████████████████████████████| 400/400 [01:03<00:00,  6.33it/s]
Loss:  122.74836730957031
RMSE:  40.597892012203054


# Matern12

In [23]:
for i in range(3):
    !python train.py 0 matern12 {i} {DATA}

Fold:  0
Random State:  0
100%|█████████████████████████████████████████| 400/400 [01:21<00:00,  4.92it/s]
Loss:  36.87507247924805
RMSE:  23.763939929331915
Fold:  0
Random State:  1
100%|█████████████████████████████████████████| 400/400 [01:22<00:00,  4.84it/s]
Loss:  58.97638702392578
RMSE:  23.69378629463355
Fold:  0
Random State:  2
100%|█████████████████████████████████████████| 400/400 [01:21<00:00,  4.88it/s]
Loss:  52.52491760253906
RMSE:  24.133128159398446


In [24]:
for i in range(1):
    !python train.py 1 matern12 {i} {DATA}

Fold:  1
Random State:  0
100%|█████████████████████████████████████████| 400/400 [01:21<00:00,  4.89it/s]
Loss:  36.9588623046875
RMSE:  26.163400150098543


In [25]:
for i in range(1):
    !python train.py 2 matern12 {i} {DATA}

Fold:  2
Random State:  0
100%|█████████████████████████████████████████| 400/400 [01:21<00:00,  4.88it/s]
Loss:  36.80494689941406
RMSE:  25.188503441660355


# Matern32

In [19]:
for i in range(3):
    !python train.py 0 matern32 {i} {DATA}

Fold:  0
Random State:  0
100%|█████████████████████████████████████████| 400/400 [01:15<00:00,  5.27it/s]
Loss:  80.84425354003906
RMSE:  36.44012066979096
Fold:  0
Random State:  1
100%|█████████████████████████████████████████| 400/400 [01:15<00:00,  5.26it/s]
Loss:  116.85900115966797
RMSE:  37.43356569493485
Fold:  0
Random State:  2
100%|█████████████████████████████████████████| 400/400 [01:15<00:00,  5.28it/s]
Loss:  110.75006866455078
RMSE:  38.340028961798204


In [20]:
for i in range(3):
    !python train.py 1 matern32 {i} {DATA}

Fold:  1
Random State:  0
100%|█████████████████████████████████████████| 400/400 [01:16<00:00,  5.25it/s]
Loss:  84.01675415039062
RMSE:  44.1776088626254
Fold:  1
Random State:  1
100%|█████████████████████████████████████████| 400/400 [01:15<00:00,  5.28it/s]
Loss:  122.46861267089844
RMSE:  42.84193880823613
Fold:  1
Random State:  2
100%|█████████████████████████████████████████| 400/400 [01:15<00:00,  5.28it/s]
Loss:  116.0630874633789
RMSE:  42.398329897057344


In [21]:
for i in range(3):
    !python train.py 2 matern32 {i} {DATA}

Fold:  2
Random State:  0
100%|█████████████████████████████████████████| 400/400 [01:15<00:00,  5.28it/s]
Loss:  83.31896209716797
RMSE:  36.92540378742489
Fold:  2
Random State:  1
100%|█████████████████████████████████████████| 400/400 [01:15<00:00,  5.27it/s]
Loss:  120.51886749267578
RMSE:  37.7904018869487
Fold:  2
Random State:  2
100%|█████████████████████████████████████████| 400/400 [01:15<00:00,  5.28it/s]
Loss:  114.47006225585938
RMSE:  38.5746025455807


# Matern52

In [47]:
for i in [8]:
    !python train.py 0 matern52 {i} {DATA}

Fold:  0
Random State:  8
100%|█████████████████████████████████████████| 400/400 [01:48<00:00,  3.69it/s]
Loss:  64.68551635742188
RMSE:  24.106531594648022


In [48]:
for i in [1]:
    !python train.py 1 matern52 {i} {DATA}

Fold:  1
Random State:  1
100%|█████████████████████████████████████████| 400/400 [01:48<00:00,  3.68it/s]
Loss:  91.060302734375
RMSE:  28.64730254052854


In [46]:
for i in range(1):
    !python train.py 2 matern52 {i} {DATA}

Fold:  2
Random State:  0
100%|█████████████████████████████████████████| 400/400 [01:48<00:00,  3.70it/s]
Loss:  54.811153411865234
RMSE:  25.932248269404244


# Matern+Rbf

In [36]:
for i in range(1):
    !python train.py 0 matern_rbf {i} {DATA}

Fold:  0
Random State:  0
100%|█████████████████████████████████████████| 400/400 [01:36<00:00,  4.15it/s]
Loss:  51.68968963623047
RMSE:  35.40558784464104


In [37]:
for i in range(1):
    !python train.py 1 matern_rbf {i} {DATA}

Fold:  1
Random State:  0
 66%|██████████████████████████▊              | 262/400 [01:03<00:33,  4.10it/s]
Loss:  65.31652069091797
RMSE:  39.69504642436942


In [38]:
for i in range(1):
    !python train.py 2 matern_rbf {i} {DATA}

Fold:  2
Random State:  0
100%|█████████████████████████████████████████| 400/400 [01:35<00:00,  4.18it/s]
Loss:  53.060482025146484
RMSE:  34.31517987053381


# Matern*Rbf

In [39]:
for i in range(1):
    !python train.py 0 maternXrbf {i} {DATA}

Fold:  0
Random State:  0
100%|█████████████████████████████████████████| 400/400 [01:40<00:00,  3.98it/s]
Loss:  105.36382293701172
RMSE:  37.8294837421403


In [40]:
for i in range(1):
    !python train.py 1 maternXrbf {i} {DATA}

Fold:  1
Random State:  0
100%|█████████████████████████████████████████| 400/400 [01:40<00:00,  3.98it/s]
Loss:  110.00485229492188
RMSE:  46.02174727223512


In [41]:
for i in range(1):
    !python train.py 2 maternXrbf {i} {DATA}

Fold:  2
Random State:  0
100%|█████████████████████████████████████████| 400/400 [01:40<00:00,  3.98it/s]
Loss:  106.90682983398438
RMSE:  39.36334184754953


In [39]:
!python test.py 0 rbf "final_models/march_data/rbf_fold_0_random_state_0" march
!python test.py 1 rbf "final_models/march_data/rbf_fold_1_random_state_1" march
!python test.py 2 rbf "final_models/march_data/rbf_fold_2_random_state_0" march

!python test.py 0 matern12 "final_models/march_data/matern12_fold_0_random_state_8" march
!python test.py 1 matern12 "final_models/march_data/matern12_fold_1_random_state_9" march
!python test.py 2 matern12 "final_models/march_data/matern12_fold_2_random_state_0" march

!python test.py 0 matern32 "final_models/march_data/matern32_fold_0_random_state_8" march
!python test.py 1 matern32 "final_models/march_data/matern32_fold_1_random_state_9" march
!python test.py 2 matern32 "final_models/march_data/matern32_fold_2_random_state_0" march

!python test.py 0 matern52 "final_models/march_data/matern52_fold_0_random_state_8" march
!python test.py 1 matern52 "final_models/march_data/matern52_fold_1_random_state_1" march
!python test.py 2 matern52 "final_models/march_data/matern52_fold_2_random_state_0" march

!python test.py 0 matern_rbf "final_models/march_data/matern_rbf_fold_0_random_state_0" march
!python test.py 1 matern_rbf "final_models/march_data/matern_rbf_fold_1_random_state_0" march
!python test.py 2 matern_rbf "final_models/march_data/matern_rbf_fold_2_random_state_0" march

!python test.py 0 maternXrbf "final_models/march_data/maternXrbf_fold_0_random_state_0" march
!python test.py 1 maternXrbf "final_models/march_data/maternXrbf_fold_1_random_state_0" march
!python test.py 2 maternXrbf "final_models/march_data/maternXrbf_fold_2_random_state_0" march

Fold:  0
Data received
RMSE:  25.176939496415933
30.315013885498047
Fold:  1
Data received
RMSE:  30.270843600669483
47.535396575927734
Fold:  2
Data received
RMSE:  26.41725059551385
29.52050018310547
Fold:  0
Data received
RMSE:  24.165682804071785
14.335278511047363
Fold:  1
Data received
RMSE:  26.649889229851766
21.205848693847656
Fold:  2
Data received
RMSE:  27.03131618611529
9.655587196350098
Fold:  0
Data received
RMSE:  23.39121079091886
21.215749740600586
Fold:  1
Data received
RMSE:  27.329625499041423
28.214588165283203
Fold:  2
Data received
RMSE:  25.99589387881733
18.72560691833496
Fold:  0
Data received
RMSE:  24.106531594648022
25.235517501831055
Fold:  1
Data received
RMSE:  28.64730254052854
38.26065444946289
Fold:  2
Data received
RMSE:  25.932248269404244
21.20368766784668
^C
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    import gpytorch
  File "/opt/conda/lib/python3.7/site-packages/gpytorch/__init__.py", line 2, in <module>
    from

UnboundLocalError: local variable 'child' referenced before assignment

## WIN_LOSS

In [19]:
for fold in [0,1,2]:
    print("Fold: ", fold)
    !python win_loss.py ../final_preds/march_nsgp_data/matern12_fold_{fold}.csv.gz ../nsgp_results/nsgp_res_fold{fold}longitude@latitude@humidity@temperature@weather@wind_direction@wind_speed@delta_t_contrbf.csv

Fold:  0
% win Series 1: 56.47849462365591
% win Series 2: 43.52150537634409
Fold:  1
% win Series 1: 57.916666666666664
% win Series 2: 42.083333333333336
Fold:  2
% win Series 1: 59.556451612903224
% win Series 2: 40.443548387096776


In [20]:
for fold in [0,1,2]:
    print("Fold: ", fold)
    !python win_loss.py ../final_preds/march_nsgp_data/matern12_fold_{fold}.csv.gz ../ml_results/fold{fold}/RF_scaled.csv.gz

Fold:  0
% win Series 1: 50.685483870967744
% win Series 2: 49.314516129032256
Fold:  1
% win Series 1: 53.696236559139784
% win Series 2: 46.303763440860216
Fold:  2
% win Series 1: 50.376344086021504
% win Series 2: 49.623655913978496


In [21]:
for fold in [0,1,2]:
    print("Fold: ", fold)
    !python win_loss.py ../nsgp_results/nsgp_res_fold{fold}longitude@latitude@humidity@temperature@weather@wind_direction@wind_speed@delta_t_contrbf.csv ../ml_results/fold{fold}/RF_scaled.csv.gz

Fold:  0
% win Series 1: 47.37903225806452
% win Series 2: 52.62096774193548
Fold:  1
% win Series 1: 46.895161290322584
% win Series 2: 53.104838709677416
Fold:  2
% win Series 1: 42.204301075268816
% win Series 2: 57.795698924731184


# Getting Losses

In [40]:
!python train.py 0 rbf 0 march
!python train.py 1 rbf 1 march
!python train.py 2 rbf 0 march

!python train.py 0 matern12 8 march
!python train.py 1 matern12 9 march
!python train.py 2 matern12 0 march

!python train.py 0 matern32 8 march
!python train.py 1 matern32 9 march
!python train.py 2 matern32 0 march

!python train.py 0 matern52 8 march
!python train.py 1 matern52 1 march
!python train.py 2 matern52 0 march

!python train.py 0 matern_rbf 0 march
!python train.py 1 matern_rbf 0 march
!python train.py 2 matern_rbf 0 march

!python train.py 0 maternXrbf 0 march
!python train.py 1 maternXrbf 0 march
!python train.py 2 maternXrbf 0 march

Fold:  0
Random State:  0
100%|█████████████████████████████████████████| 400/400 [01:05<00:00,  6.07it/s]
Loss:  65.70559692382812
RMSE:  25.176939496415933
Fold:  1
Random State:  1
100%|█████████████████████████████████████████| 400/400 [01:06<00:00,  6.03it/s]
Loss:  102.3407974243164
RMSE:  30.270843600669483
Fold:  2
Random State:  0
100%|█████████████████████████████████████████| 400/400 [01:06<00:00,  6.04it/s]
Loss:  67.06449890136719
RMSE:  26.41725059551385
Fold:  0
Random State:  8
100%|█████████████████████████████████████████| 400/400 [01:21<00:00,  4.88it/s]
Loss:  48.87971115112305
RMSE:  24.165682804071785
Fold:  1
Random State:  9
100%|█████████████████████████████████████████| 400/400 [01:23<00:00,  4.81it/s]
Loss:  68.29399871826172
RMSE:  26.649889229851766
Fold:  2
Random State:  0
100%|█████████████████████████████████████████| 400/400 [01:22<00:00,  4.86it/s]
Loss:  46.083152770996094
RMSE:  26.21899947472983
Fold:  0
Random State:  8
100%|██████████████████████

In [7]:
for i in [5]:
    !python train.py 0 local_p_delta {i} march_nsgp

Fold:  0
Random State:  5
Initial Period Length: Parameter containing:
tensor([[5.]], device='cuda:0', requires_grad=True)
100%|█████████████████████████████████████████| 400/400 [01:30<00:00,  4.44it/s]
Learnt Period Length: Parameter containing:
tensor([[3.3894]], device='cuda:0', requires_grad=True)
Loss:  99.39817810058594
RMSE:  31.898585091380454


In [3]:
# Only on Local Periodic Data
for fold in [1,2]:
    print("FOLD: ", fold)
    for i in [5]:
        !python train.py {fold} local_p_delta {i} march_nsgp

FOLD:  1
Fold:  1
Random State:  5
Initial Period Length: Parameter containing:
tensor([[5.]], device='cuda:0', requires_grad=True)
100%|█████████████████████████████████████████| 400/400 [01:29<00:00,  4.48it/s]
Learnt Period Length: Parameter containing:
tensor([[3.3964]], device='cuda:0', requires_grad=True)
Loss:  94.25504302978516
RMSE:  34.50554684897821
FOLD:  2
Fold:  2
Random State:  5
Initial Period Length: Parameter containing:
tensor([[5.]], device='cuda:0', requires_grad=True)
100%|█████████████████████████████████████████| 400/400 [01:29<00:00,  4.47it/s]
Learnt Period Length: Parameter containing:
tensor([[3.4178]], device='cuda:0', requires_grad=True)
Loss:  101.36831665039062
RMSE:  30.52990215209717


In [16]:
!python test.py 0 local_p_delta 'final_models/march_nsgp_data/local_p_delta_fold_0_random_state_5' march_nsgp

Fold:  0
Data received
RMSE:  31.244683829276585


In [17]:
!python test.py 1 local_p_delta 'final_models/march_nsgp_data/local_p_delta_fold_1_random_state_5' march_nsgp

Fold:  1
Data received
RMSE:  34.67969999121579


In [18]:
!python test.py 2 local_p_delta 'final_models/march_nsgp_data/local_p_delta_fold_2_random_state_5' march_nsgp

Fold:  2
Data received
RMSE:  30.068043471482337


In [22]:
# Learnt Length Scale:
!python test.py 0 matern12 "final_models/march_data_no_ARD/matern12_fold_0_random_state_0" march

Fold:  0
Data received
{'training': False, '_parameters': OrderedDict([('raw_lengthscale', Parameter containing:
tensor([[0.7346]], device='cuda:0', requires_grad=True))]), '_buffers': OrderedDict([('active_dims', None)]), '_non_persistent_buffers_set': set(), '_backward_hooks': OrderedDict(), '_is_full_backward_hook': None, '_forward_hooks': OrderedDict(), '_forward_pre_hooks': OrderedDict(), '_state_dict_hooks': OrderedDict(), '_load_state_dict_pre_hooks': OrderedDict([(0, <bound method Module._load_state_hook_ignore_shapes of MaternKernel(
  (raw_lengthscale_constraint): Positive()
  (distance_module): Distance()
)>)]), '_modules': OrderedDict([('raw_lengthscale_constraint', Positive()), ('distance_module', Distance())]), '_added_loss_terms': OrderedDict(), '_priors': OrderedDict(), '_constraints': OrderedDict([('raw_lengthscale_constraint', Positive())]), '_strict_init': True, '_load_strict_shapes': True, '_batch_shape': torch.Size([]), 'ard_num_dims': None, 'eps': 1e-06, '_Kernel_